services:
  - type: web
    name: capstone-web-service
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --workers 1 --threads 2 --timeout 120
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: true